# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a77f90ebf47402901082cbf6af2891a35fdfe6ae65d82c6d0871075cbf20b380bf70d4d3d2531f5df6b312d41eb506f4816c4c4f33b3168326709b78b56d99fc

test:
  secret_key_base: b9b5f25cb15c536d2f90353b68d2cabb51b247060b309e61e09c7f89d334dec0a81093a1013892c0cc06f621755dd8ffac970935cb948d52fc695d2b5c50df0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
